### PR TITLE
Update dataplane license for CNCF requirements

### LINKED ISSUE #78: Change dataplane licensing to meet CNCF requirements
In the midst of our [migration of this project to Kubernetes SIGs](https://github.com/kubernetes/org/issues/3875) and trying to [get approved for inclusion of GPLv2 code](https://github.com/cncf/foundation/issues/474) we learned that a combination of `GPLv2 + BSD-2-Clause` licensing for eBPF code is currently [allowed licensing](https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md) for CNCF inclusion with [precedents](https://github.com/cilium/cilium/issues/18823).

The purpose of this task is to update our licensing of the dataplane code from `GPLv2` to `GPLv2 + BSD-2-Clause` to get our [migration](https://github.com/Kong/blixt/discussions/42) moving along.

### PR DESCRIPTION
**Pull request by shaneutt**
Changes the dataplane licensing from `GPLv2` to dual-licensed `GPLv2 + BSD-2-Clause` as per CNCF requirements as outlined in #78.

Resolves #78

### CODE REVIEW

**Review by astoycos — APPROVED** [review]
/lgtm 

Thanks for taking care of this!

**Review by mlavacca — APPROVED** [review]
lgtm 👍

**Comment by robscott** [comment]
Thanks!

/lgtm

**Comment by rushi47** [comment]
Thank you shane 👍 
 lgtm

**Review by wheelerlaw — COMMENTED** [review]
as a contributor to the dataplane code, I approve of the change from GPLv2 to GPLv2 or BSD-2-Clause licensing

**Review by rushi47 — COMMENTED** [review]
This looks perfect, thanks for taking care of this !
Lgtm 👍

**Review by synthe102 — COMMENTED** [review]
As a contributor to the dataplane code, I approve of the change from GPLv2 to GPLv2 or BSD-2-Clause licensing

**Pull request merged**
